// ignore_for_file: unused_import

import 'package:flutter/material.dart';

import 'package:http/http.dart' as http;
import 'dart:convert';

import 'Autogenerated .dart';

void main() async {
  var str = await fetchAlbun();
  List<Autogenerated> array = [];
  for (var i = 0; i < 100; i++) {
    array.add(Autogenerated.fromJson(str[i]));
  }
  for (final e in array) {
    print(e.id);
    print(e.title);
    print(e.userId);
  }
}

Future<dynamic> fetchAlbun() async {
  final url = 'https://jsonplaceholder.typicode.com/albums';
  final res = await http.get(Uri.parse(url));

  if (res.statusCode == 200) {
    var obj = json.decode(res.body);
    return obj;
  } else {
    throw Exception("error");
  }
}
